version: '3.9'
services:
  api:
    extends:
      file: ./hitech-market_api/docker-compose.yml
      service: app

  mongodb:
    extends:
      file: ./hitech-market_api/docker-compose.yml
      service: mongodb

  web:
    extends:
      file: ./hitech-market_web/docker-compose.yml
      service: app
